/* Generated By:JavaCC: Do not edit this line. Aula1TreeConstants.java Version 7.0.12 */
package parser;

public interface Aula1TreeConstants
{
  public int JJTSTART = 0;
  public int JJTMAIN = 1;
  public int JJTCOMANDOS = 2;
  public int JJTBLOCO = 3;
  public int JJTATRIBUICAO = 4;
  public int JJTCONDICIONAL = 5;
  public int JJTREPETICAO = 6;
  public int JJTTIPODADO = 7;
  public int JJTVARIAVEL = 8;
  public int JJTDADO = 9;
  public int JJTOPERACAO = 10;
  public int JJTTERMOOUFATORARITMETICO = 11;
  public int JJTSTRING = 12;
  public int JJTBOOL = 13;
  public int JJTPARA = 14;
  public int JJTENQUANTO = 15;
  public int JJTEXPRESSAO = 16;
  public int JJTTERMOEXPRESSAO = 17;
  public int JJTFATOREXPRESSAO = 18;
  public int JJTCOMPARACAO = 19;
  public int JJTOPERADORCOMPARACAO = 20;
  public int JJTABRECHAVE = 21;
  public int JJTFECHACHAVE = 22;
  public int JJTINTEIROTIPO = 23;
  public int JJTFLOATTIPO = 24;
  public int JJTSTRINGTIPO = 25;
  public int JJTBOLLEANTIPO = 26;
  public int JJTCARACTERE = 27;
  public int JJTDIGITO = 28;
  public int JJTPONTO = 29;
  public int JJTTRUEBLOCO = 30;
  public int JJTFALSEBLOCO = 31;
  public int JJTIFBLOCO = 32;
  public int JJTELSEBLOCO = 33;
  public int JJTFORBLOCO = 34;
  public int JJTPONTOVIRGULA = 35;
  public int JJTVIRGULA = 36;
  public int JJTIGUAL = 37;
  public int JJTABREPARENTESES = 38;
  public int JJTIGUALIGUAL = 39;
  public int JJTMAIOR = 40;
  public int JJTMAIORIGUAL = 41;
  public int JJTMENOR = 42;
  public int JJTMENORIGUAL = 43;
  public int JJTMENORMAIOR = 44;
  public int JJTFECHAPARENTESES = 45;
  public int JJTMAIS = 46;
  public int JJTMENOS = 47;
  public int JJTMULTIPLICACAO = 48;
  public int JJTDIVISAO = 49;
  public int JJTPOTENCIA = 50;
  public int JJTWHILEBLOCO = 51;
  public int JJTOPERADORLOGICO = 52;
  public int JJTMAISMAIS = 53;
  public int JJTMENOSMENOS = 54;
  public int JJTMAISMENOS = 55;
  public int JJTMENOSMAIS = 56;


  public String[] jjtNodeName = {
    "Start",
    "main",
    "comandos",
    "bloco",
    "atribuicao",
    "condicional",
    "repeticao",
    "tipoDado",
    "variavel",
    "dado",
    "operacao",
    "termoOuFatorAritmetico",
    "string",
    "bool",
    "para",
    "enquanto",
    "expressao",
    "termoExpressao",
    "fatorExpressao",
    "comparacao",
    "operadorComparacao",
    "abreChave",
    "fechaChave",
    "inteiroTipo",
    "floatTipo",
    "stringTipo",
    "bolleanTipo",
    "caractere",
    "digito",
    "ponto",
    "trueBloco",
    "falseBloco",
    "ifBloco",
    "elseBloco",
    "forBloco",
    "pontoVirgula",
    "virgula",
    "igual",
    "abreParenteses",
    "igualIgual",
    "maior",
    "maiorIgual",
    "menor",
    "menorIgual",
    "menorMaior",
    "fechaParenteses",
    "mais",
    "menos",
    "multiplicacao",
    "divisao",
    "potencia",
    "whileBloco",
    "operadorLogico",
    "maismais",
    "menosmenos",
    "maismenos",
    "menosmais",
  };
}
/* JavaCC - OriginalChecksum=0219b50c701491f4bae07503d1b02e2b (do not edit this line) */
